spring.application.name=RestApiAppActuator
server.port = 8284


#It means I want to use all the builtin endPoints
management.endpoints.web.exposure.include=* 


#It means I want to exclude these builtin endPoints
management.endpoints.web.exposure.exclude=env,beans 


management.endpoint.shutdown.enabled=true