spring.application.name=TouristManagementAPIGlobalExceptionHandling

server.port=8484
server.servlet.context-path=/TouristManagementAPI

#Datasource Config
spring.datasource.url=jdbc:mysql://localhost:3306/finishers
spring.datasource.username=navi
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update