spring.application.name=TouristManagementAPI
server.port=8484
#
#server:
#  port:8484

server.servlet.context-path=/TouristManagementAPI
#
#server:
#  servlet:
#    context-path:/TouristManagementAPI

#Datasource Config
spring.datasource.url=jdbc:mysql://localhost:3306/finishers
spring.datasource.username=navi
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
#
#spring:
#  datasource:
#    url:jdbc:mysql://localhost:3306/finishers
#    username:navi
#    password:password
#  jpa:
#    hibernate:
#      ddl-auto:update
